### ISSUE TITLE
Give Precision Inspections a call RE their top 7 questions

### ISSUE THREAD

**Issue by ElliottAssetBuilders** [patassetbuilders/social-media-#193]
I will give Precision a call RE their top 7 questions and what they should be. If I don't get a response we'll close the issue

**Comment by LiamAssetBuilders** [comment]
# Top 8 Questions/Answers have been received




1.Do they have practical experience with residential and commercial building 

-  has been a licensed builders completing projects since 1991 

2.What are their Qualifications 

-  Associate diploma of building
- Cert of urban pest control 
- Associate diploma of applied science 
- Grad cert of business ministration

3.Will they provide their CV 

- see attached 

4.Do they have an online client portal

- Yes a simple in house designed agile and easy to use program to keep clients up to date 

5.Can I access my reports online 

- Yes, through our client portal your full history of reports are available.

6.Can your reports be used for Legal/NCAT matters
 
- Yes, Gerard is a fully qualified to produce and meet the requirement of all expert witness reports 

7.What is your expert witness experiance 

-   Gerard has testified as expert witness in over 500 cases over the past 10 years.  Including five cases through the supreme court. 

8.Do they have upfront pricing for standard reports ? 

- Yes    see attached.
