### ISSUE TITLE
Payment details for IBW also sort out website costs

### ISSUE THREAD

**Issue by patassetbuilders** [patassetbuilders/social-media-#300]
Test email sent, we need payment details,

Regards,

Pat

**Comment by patassetbuilders** [comment]
all workflows have been switched on

**Comment by Deeds69** [comment]
Have sent Karen the link to our payment details form. Have not received the completed form back to date.
I have Set up the recurring transaction in Xero for monthly charge of $40, 1st charge was to due to commence 1st July & Due 8th July.
Have also sent invoice for annual website hosting fee $360 - due date was 30th June has not been paid to date.

**Comment by patassetbuilders** [comment]
Bill raised in accounting system
